services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "qwe"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qwe"]
      interval: 10s
      timeout: 10s
      retries: 10

  app:
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_CONN: "postgres://postgres:admin@postgres:5432/qwe?sslmode=disable"
    ports:
      - "8080:8080"
